version: '3.8'

networks:
    backend:
        driver: bridge

services:
  php:
    build:
      context: ./docker/php
      args:
        version: ${DOCKER_PHP_VERSION}
    working_dir: /var/www/html/
    container_name: ${DOCKER_CONTAINER_NAME}.php
    hostname: backend.${DOCKER_CONTAINER_NAME}.php
    environment:

      PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}

      PHP_IDE_CONFIG: serverName=${DOCKER_CONTAINER_NAME}
    volumes:
      - .:/var/www/html/
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - backend

  webserver:
    build:
      context: ./docker/webserver
      args:
        version: ${DOCKER_WEBSERVER_VERSION}
    working_dir: /var/www/html/
    container_name: ${DOCKER_CONTAINER_NAME}.webserver
    hostname: backend.${DOCKER_CONTAINER_NAME}.webserver
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html/
      - ./docker/webserver/conf.d/:/etc/nginx/conf.d/
    ports:
      - ${DOCKER_WEBSERVER_HTTP_PORT}:80
      - ${DOCKER_WEBSERVER_HTTPS_PORT}:443
    depends_on:
      - php
    networks:
      - backend
